### ISSUE TITLE
A page which is not an OCaml doc gets autoconverted to the new Reason doc stylesheet

### ISSUE THREAD

**Issue by xennygrimmato** [rickyvetter/reason-tools#13]
When I go to the URL: [https://www.tjson.org/spec/](https://www.tjson.org/spec/), the extension automatically swaps the stylesheet and detects the page to be an OCaml doc page.
This is a false positive.

**Comment by rickyvetter** [comment]
Thanks for the report - this passes the check here because this page uses the same rel syntax with Chapter and Contents. I think Chapter and Contents can be removed - but I'll check with my test pages to be sure.

https://github.com/rickyvetter/reason-tools/blob/master/src/AutoConversionPrompt.js#L31

**Comment by rickyvetter** [comment]
Fixed in d1df6e8
